### PR TITLE
fix(build): fix build by enabling the POSIX API

### PR DESCRIPTION
**Pull request by gminn**
### Summary

 Zephyr [recently deprecated](https://github.com/zephyrproject-rtos/zephyr/pull/69950)
the `CONFIG_NET_SOCKETS_POSIX_NAMES` option, which was was previously
 `y` by default when `CONFIG_POSIX_API=n` but is now `n` by default.
 This option matters because it adds the POSIX API to the `net/socket.h`
 header, which we reference in `memfault_platform_http.c`. This fix
 instead makes our http client code include the `posix/*` headers to get
 the POSIX API.

 ### Test Plan

 Builds successfully.

### CODE REVIEW

**Comment by gminn** [comment]
* **#1** <a href="https://app.graphite.dev/github/pr/memfault/memfault-zephyr-http-example/1?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @gminn and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by noahp — APPROVED** [review]
Oh nice, tyty! Do you think we need this in the SDK?

**Comment by gminn** [comment]
@noahp Probably, checking now

**Comment by gminn** [comment]
> @noahp Probably, checking now

@noahp argh there's some other TFM build error when I pointed to master, punting that investigation for now. Added a ticket so we wouldn't forget: https://linear.app/memfault/issue/MCU-350/investigate-if-we-need-to-select-config-posix-api-when-config-memfault

**Pull request merged**
